Repository giantswarm/kubectl-gs, pull requests merged in 2022-02, with the labels that each got.

#659 Add release notes configuration
  .github/release.yml
Labels: dev-change

#660 Add `--keep-context` flag to `login` command
  CHANGELOG.md
  cmd/login/auth.go
  cmd/login/flag.go
  cmd/login/runner.go
Labels: feature

#592 enable unsafe login for older clusters in default namespace
  CHANGELOG.md
  cmd/login/clientcert.go
  cmd/login/runner.go
Labels: feature

#665 Update dependencies
  go.mod
  go.sum
Labels: dependencies

#655 Drop client wrappers
  cmd/get/apps/runner.go
  cmd/get/capi/runner.go
  cmd/get/catalogs/runner.go
  cmd/get/clusters/printer_test.go
  cmd/get/clusters/provider/azure.go
  cmd/get/clusters/runner.go
  cmd/get/clusters/runner_test.go
  cmd/get/nodepools/printer_test.go
  cmd/get/nodepools/runner.go
  cmd/get/nodepools/runner_test.go
  cmd/get/releases/runner.go
  cmd/login/clientcert.go
  cmd/login/runner.go
  cmd/template/cluster/provider/aws.go
  cmd/template/cluster/provider/azure.go
  cmd/template/cluster/provider/common.go
  cmd/template/cluster/provider/templates/aws/cluster.go
  cmd/template/cluster/runner.go
  cmd/template/networkpool/runner.go
  cmd/template/nodepool/provider/azure.go
  cmd/template/nodepool/provider/common.go
  cmd/template/nodepool/provider/templates/aws/nodepool.go
  cmd/template/nodepool/runner.go
  cmd/update/app/runner.go
  cmd/update/app/runner_test.go
  cmd/update/cluster/runner.go
  cmd/update/cluster/runner_test.go
  internal/key/common.go
  pkg/app/service.go
  pkg/commonconfig/commonconfig.go
  pkg/data/client/client.go
  pkg/data/client/client_fake.go
  pkg/data/client/error.go
  pkg/data/client/k8sclient_fake.go
  pkg/data/domain/app/service.go
  pkg/data/domain/app/service_fake.go
  pkg/data/domain/catalog/service.go
  pkg/data/domain/clientcert/service.go
  pkg/data/domain/cluster/aws.go
  pkg/data/domain/cluster/azure.go
  pkg/data/domain/cluster/common.go
  pkg/data/domain/cluster/service.go
  pkg/data/domain/cluster/service_fake.go
  pkg/data/domain/nodepool/aws.go
  pkg/data/domain/nodepool/azure.go
  pkg/data/domain/nodepool/service.go
  pkg/data/domain/nodepool/service_fake.go
  pkg/data/domain/organization/service.go
  pkg/data/domain/release/common.go
  pkg/data/domain/release/service.go
  pkg/helmbinary/service.go
  pkg/id/id.go
  pkg/id/id_test.go
  pkg/scheme/scheme.go
Labels: refactor

#661 add support for self-contained kubeconfig in MC case
  CHANGELOG.md
  cmd/login/auth.go
  cmd/login/clientcert.go
  cmd/login/flag.go
  cmd/login/runner.go
Labels: feature

#687 Dependencies
  go.mod
  go.sum
Labels: dependencies
